### ISSUE TITLE
Move to GitHub package registry?

### ISSUE THREAD

**Issue by bootstraponline** [runningcode/fladle#74]
Hey, I am looking at publishing Flank to the GitHub package registry and dropping bintray. Let me know if this would cause any problems. Bintray has reliability issues. I'm hoping GitHub offers a more stable and performant artifact service.

https://help.github.com/en/articles/configuring-gradle-for-use-with-github-package-registry

**Comment by runningcode** [comment]
Hey, thanks for opening this issue. Will you continue to publish to bintray in addition to github package registry? If so, I see no problem with this. Otherwise, older clients will not be able to update the flank version without also updating the fladle version.

Curious, why not use maven central though? Additional repositories slow down build performance in Gradle. The Fladle plugin currrently adds the bintray repository. We can swap that out for the Github package registry for future versions, but if it were published to maven central, we wouldn't need to add either.

**Comment by bootstraponline** [comment]
Thanks, that's good feedback. I'll look into Maven Central publishing.

**Comment by bootstraponline** [comment]
I opened an issue upstream to track progress.

It looks like bintray supports syncing to maven central.

- https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/
